# Generated by Django 5.2.3 on 2025-06-13 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hometouser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
