# Generated by Django 5.2.3 on 2025-06-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_task_user_alter_category_user_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_category',
            field=models.CharField(default='To-Do', max_length=50),
            preserve_default=False,
        ),
    ]
