# Generated by Django 5.2.3 on 2025-06-15 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_task_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_category',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(default='To-Do', on_delete=django.db.models.deletion.CASCADE, to='board.category'),
            preserve_default=False,
        ),
    ]
